import { Buffer } from 'buffer'
import { Stats, promises as fs } from 'fs'
import os from 'os'
import { basename, join, resolve } from 'path'

import copyFile from 'cp-file'
import deleteFiles from 'del'
import pMap from 'p-map'

import { startZip, addZipFile, addZipContent, endZip, ZipArchive } from '../../../archive.js'
import type { FeatureFlags } from '../../../feature_flags.js'
import { mkdirAndWriteFile } from '../../../utils/fs.js'

import { getEntryFile } from './entry_file.js'
import { getFileExtensionForFormat, ModuleFormat } from './module_format.js'
import { normalizeFilePath } from './normalize_path.js'

// Taken from https://www.npmjs.com/package/cpy.
const COPY_FILE_CONCURRENCY = os.cpus().length === 0 ? 2 : os.cpus().length * 2

// Sub-directory to place all user-defined files  (i.e. everything other than
// the entry file generated by zip-it-and-ship-it).
const DEFAULT_USER_SUBDIRECTORY = 'src'

export type ArchiveFormat = 'none' | 'zip'

interface ZipNodeParameters {
  aliases?: Map<string, string>
  basePath: string
  destFolder: string
  extension: string
  featureFlags: FeatureFlags
  filename: string
  mainFile: string
  moduleFormat: ModuleFormat
  rewrites?: Map<string, string>
  srcFiles: string[]
}

const createDirectory = async function ({
  aliases = new Map(),
  basePath,
  destFolder,
  extension,
  featureFlags,
  filename,
  mainFile,
  moduleFormat,
  rewrites = new Map(),
  srcFiles,
}: ZipNodeParameters) {
  const entryFile = getEntryFile({
    commonPrefix: basePath,
    mainFile,
    moduleFormat,
    userNamespace: DEFAULT_USER_SUBDIRECTORY,
  })
  const entryFileExtension = getFileExtensionForFormat(moduleFormat, featureFlags)
  const entryFilename = basename(filename, extension) + entryFileExtension
  const functionFolder = join(destFolder, basename(filename, extension))
  const entryFilePath = resolve(functionFolder, entryFilename)

  // Deleting the functions directory in case it exists before creating it.
  await deleteFiles(functionFolder, { force: true })
  await fs.mkdir(functionFolder, { recursive: true })

  // Writing entry file.
  await fs.writeFile(entryFilePath, entryFile)

  // Copying source files.
  await pMap(
    srcFiles,
    (srcFile) => {
      const destPath = aliases.get(srcFile) || srcFile
      const normalizedDestPath = normalizeFilePath({
        commonPrefix: basePath,
        path: destPath,
        userNamespace: DEFAULT_USER_SUBDIRECTORY,
      })
      const absoluteDestPath = join(functionFolder, normalizedDestPath)

      if (rewrites.has(srcFile)) {
        return mkdirAndWriteFile(absoluteDestPath, rewrites.get(srcFile) as string)
      }

      return copyFile(srcFile, absoluteDestPath)
    },
    { concurrency: COPY_FILE_CONCURRENCY },
  )

  return functionFolder
}

const createZipArchive = async function ({
  aliases,
  basePath,
  destFolder,
  extension,
  featureFlags,
  filename,
  mainFile,
  moduleFormat,
  rewrites,
  srcFiles,
}: ZipNodeParameters) {
  const destPath = join(destFolder, `${basename(filename, extension)}.zip`)
  const { archive, output } = startZip(destPath)
  const entryFileExtension = getFileExtensionForFormat(moduleFormat, featureFlags)
  const entryFilename = basename(filename, extension) + entryFileExtension
  const entryFilePath = resolve(basePath, entryFilename)

  // We don't need an entry file if it would end up with the same path as the
  // function's main file.
  const needsEntryFile = entryFilePath !== mainFile

  // There is a naming conflict with the entry file if one of the supporting
  // files (i.e. not the main file) has the path that the entry file needs to
  // take.
  const hasEntryFileConflict = srcFiles.some((srcFile) => srcFile === entryFilePath && srcFile !== mainFile)

  // If there is a naming conflict, we move all user files (everything other
  // than the entry file) to its own sub-directory.
  const userNamespace = hasEntryFileConflict ? DEFAULT_USER_SUBDIRECTORY : ''

  if (needsEntryFile) {
    const entryFile = getEntryFile({ commonPrefix: basePath, mainFile, moduleFormat, userNamespace })

    addEntryFileToZip(archive, entryFile, basename(entryFilePath))
  }

  const srcFilesInfos = await Promise.all(srcFiles.map(addStat))

  // We ensure this is not async, so that the archive's checksum is
  // deterministic. Otherwise it depends on the order the files were added.
  srcFilesInfos.forEach(({ srcFile, stat }) => {
    zipJsFile({
      aliases,
      archive,
      commonPrefix: basePath,
      rewrites,
      srcFile,
      stat,
      userNamespace,
    })
  })

  await endZip(archive, output)

  return destPath
}

export const zipNodeJs = function ({
  archiveFormat,
  ...options
}: ZipNodeParameters & { archiveFormat: ArchiveFormat }): Promise<string> {
  if (archiveFormat === 'zip') {
    return createZipArchive(options)
  }

  return createDirectory(options)
}

const addEntryFileToZip = function (archive: ZipArchive, contents: string, filename: string) {
  const contentBuffer = Buffer.from(contents)

  addZipContent(archive, contentBuffer, filename)
}

const addStat = async function (srcFile: string) {
  const stat = await fs.lstat(srcFile)

  return { srcFile, stat }
}

const zipJsFile = function ({
  aliases = new Map(),
  archive,
  commonPrefix,
  rewrites = new Map(),
  stat,
  srcFile,
  userNamespace,
}: {
  aliases?: Map<string, string>
  archive: ZipArchive
  commonPrefix: string
  rewrites?: Map<string, string>
  stat: Stats
  srcFile: string
  userNamespace: string
}) {
  const destPath = aliases.get(srcFile) || srcFile
  const normalizedDestPath = normalizeFilePath({ commonPrefix, path: destPath, userNamespace })

  if (rewrites.has(srcFile)) {
    addZipContent(archive, rewrites.get(srcFile) as string, normalizedDestPath)
  } else {
    addZipFile(archive, srcFile, normalizedDestPath, stat)
  }
}
